
services:
  - type: cron
    name: flight-price-collector
    runtime: python
    schedule: "0 9 * * *"  # Runs daily at 9:00 UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python collector.py
    envVars:
      - key: MARKER
        sync: false  # Use Render's dashboard to set this
