

# render.yaml  (in the root of flydena-flight-collector)
services:
  - type: cron
    name: flight-price-collector
    runtime: python
    repo: https://github.com/rihua-tech/flydena-flight-collector.git
    branch: main
    schedule: "0 9 * * *"       # runs daily at 09:00 UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python collector.py
    envVars:
      - key: MARKER
        sync: false            # set in the Render dashboard
      - key: GH_TOKEN
        sync: false
      - key: GH_REPO
        value: rihua-tech/flight-price-data
